### ISSUE TITLE
Issue about inference

### ISSUE THREAD

**Issue by Joe12138** [ZikangZhou/HiVT#7]
Hello, 
        Firstly, thanks for your nice work in trajectory prediction. However, I notices that you choose the best trajectory after comparing with ground truth trajectory in validation step. However, in test step, normally, we don't know the ground truth trajectory. Could you kindly tell me how to choose candidate trajectories in the inference step in HiVT?
Best,
Joe

**Comment by ZikangZhou** [comment]
Hi,

Thanks for your interest! Trajectory prediction is inherently a multimodal problem, so most models will predict multiple plausible trajectories. As you said, it's impossible to know the ground truth in advance. Metrics that are commonly used in this field (e.g., minADE and minFDE) only provide a way to measure a model's capability of covering the ground truth in the validation dataset.

We only predict 6 trajectories for each agent (i.e., the future distribution is parameterized by a mixture of Laplace distribution with 6 modes) simply because the metrics used in Argoverse motion forecasting benchmark (minADE_6, minFDE_6, and MR_6) allow a maximum of 6 predictions per agent. I have found that the more predictions we make, the lower minADE_6 we can get (see the attached image).

You may ask: how many predictions per agent do we need?  In practice, trajectory prediction models need to collaborate with the downstream motion planning module. We don't hope to predict too many trajectories, or else the drivable area for the autonomous vehicle would be too small and the behavior of the autonomous vehicle would be too conservative. We also don't hope to predict too few trajectories, or else the model may miss a potential case and the autonomous vehicle may suffer from the risk of collisions. I can't tell you what the optimal number of predictions is, but I think it depends on the motion planning module.

<img width="303" alt="Screenshot 2022-07-04 at 11 13 58 AM" src="https://user-images.githubusercontent.com/30786563/177075275-9a1e0710-3e21-4b98-b7eb-4c67a40f03a1.png">

**Comment by Joe12138** [comment]
Hi,
    Thanks for your nice reply. 
Best, 
Joe
