### ISSUE TITLE
How can I extract one vehicle's feature from local encoder and globale interaction module?

### ISSUE THREAD

**Issue by Joe12138** [ZikangZhou/HiVT#8]
Hi, 
Thanks for your excellent work. Could you kindly tell me how to extract one vehicle feature from the output of local encoder and global interaction modules? I am new for pytorch_lightning, so I am a little confuse about it.
Best,
Joe

**Comment by ZikangZhou** [comment]
Do you mean you need one vehicle's `local_embed` and `global_embed` in the figure below? 

<img width="671" alt="Screenshot 2022-07-07 at 9 14 48 PM" src="https://user-images.githubusercontent.com/30786563/177782471-98472df8-41fc-4a29-96ab-e650f994e69e.png">

The shape of `local_embed` is [num_agents, hidden_dim], and the shape of `global_embed` is [6, num_agents, hidden_dim] (there is an additional dimension 6 here because I use a linear layer at the end of the global interactor to project `^h_1`).

**Comment by Joe12138** [comment]
Hi,
Yes, that is what I want. Thanks for your nice and patient reply!
Best,
Joe
