### ISSUE TITLE
Visualization tool for local region

### ISSUE THREAD

**Issue by Jihong-Kim97** [ZikangZhou/HiVT#9]
Hello,
First of all, thanks for your excellent work!
I wonder if there is any visualization code or tool for local regions.
I know that there is visualization tool for scenario which is provided in argoverse-api but I want to watch just local region that local encoder use to train or infer.
Thank you :)

**Comment by ZikangZhou** [comment]
Hello,

I didn't clean that part of the code, but my visualization tool is modified from [the baseline repo](https://github.com/jagjeet-singh/argoverse-forecasting). In general, you can use `get_lane_ids_in_xy_bbox()` in the map API with the target agent's position@t=20 as the query center to get nearby lanes. Some segments of these nearby lanes may not be used in training, because some lanes may be pretty long and I filter out those segments whose distance to the target agent is larger than the pre-defined radius.
